export const TOKEN_ABI = [
  'function name() view returns (string)',
  'function totalSupply() view returns (uint256)',
  'function emissionCap() view returns (uint256)',
  'function totalMinted() view returns (uint256)',
  'function setEmissionCap(uint256 newCap)',
  'function pause()',
  'function unpause()',
] as const;

export const NFT_ABI = [
  'function getEdition(uint256) view returns ((string name, string artURI, uint16 health, uint16 skill, uint16 morale, uint8 rarity, uint32 maxSupply, uint32 minted, uint64 mintStart, uint64 mintEnd, uint256 price, uint8 distribution, bool active))',
  'function editionCount() view returns (uint256)',
  'function getTierPrices() view returns (uint256[10])',
  'function tierPrice(uint256) view returns (uint256)',
  'function renamePrice() view returns (uint256)',
  'function isApprovedForAll(address, address) view returns (bool)',
  'function setApprovalForAll(address, bool)',
  'function registerReferrer()',
  'function registerEdition(string name, string artURI, uint16 health, uint16 skill, uint16 morale, uint8 rarity, uint32 maxSupply, uint64 mintStart, uint64 mintEnd, uint256 price, uint8 distribution, uint16[10] tierWeights) returns (uint256)',
  'function setEditionActive(uint256 editionId, bool active)',
  'function setEditionWindow(uint256 editionId, uint64 mintStart, uint64 mintEnd)',
  'function updateTierPrices(uint256[10] prices)',
  'function setRoyalty(address receiver, uint96 bps)',
  'function setRenamePrice(uint256 price)',
  'function setReferralLevels(uint256[] thresholds, uint16[] ratesBps)',
  'function pendingOwner() view returns (address)',
  'function acceptOwnership()',
  'function setForge(address forge)',
  'function pause()',
  'function unpause()',
  'function withdraw()',
  'event EditionRegistered(uint256 indexed editionId, string name, uint8 distribution, uint8 rarity)',
  'error InvalidEditionWindow()',
  'error InvalidEditionName()',
  'error InvalidLevels()',
  'error TransferFailed()',
] as const;

export const STAKING_ABI = [
  'function stakePair(uint256 maleId, uint256 femaleId) returns (uint256)',
  'function unstakePair(uint256)',
  'function claim(uint256)',
  'function pendingOf(uint256) view returns (uint256)',
  'function nextUnlock(uint256) view returns (uint256)',
  'function getConfig() view returns (uint256 baseRate_, uint256 wHealth_, uint256 wSkill_, uint256 wMorale_, uint256 claimBurnBps_, uint256 idealPairMultiplierBps_)',
  'function pendingOwner() view returns (address)',
  'function acceptOwnership()',
  'function setBaseRate(uint256 rate)',
  'function setWeights(uint256 wH, uint256 wS, uint256 wM)',
  'function setClaimBurnBps(uint256 bps)',
  'function setIdealPairMultiplierBps(uint256 bps)',
  'function pause()',
  'function unpause()',
  'error UnauthorizedNFT()',
  'error BaseRateTooHigh(uint256)',
  'error WeightTooHigh(uint256)',
] as const;

export const MARKETPLACE_ABI = [
  'function list(uint256 tokenId, uint96 price)',
  'function cancel(uint256)',
  'function obtain(uint256) payable',
  'function pendingOwner() view returns (address)',
  'function acceptOwnership()',
  'function getFeeConfig() view returns (address feeSink_, uint256 platformFeeBps_)',
  'function setPlatformFee(address feeSink, uint256 bps)',
  'function pause()',
  'function unpause()',
  'error FeesExceedPrice(uint256,uint256,uint256)',
  'error NotProposer(uint256)',
  'error InvalidBasisPoints(uint256)',
  'error TransferFailed()',
] as const;

export const FORGE_ABI = [
  'function requestObtain(uint8 tier, uint256 referrerCode, string name) payable returns (uint256)',
  'function claimReferralBnb()',
  'function owner() view returns (address)',
  'function acceptOwnership()',
  'function setVRFConfig(bytes32 keyHash, uint256 subId, uint32 callbackGasLimit, uint16 requestConfirmations)',
  'function withdraw()',
  'function keyHash() view returns (bytes32)',
  'function subId() view returns (uint256)',
  'function callbackGasLimit() view returns (uint32)',
  'function requestConfirmations() view returns (uint16)',
  'error CallbackGasLimitOutOfRange(uint32)',
  'error RequestConfirmationsTooLow()',
  'error NothingToRefund()',
  'error TransferFailed()',
  'event ForgeRequested(address indexed buyer, uint256 indexed requestId, uint8 tier)',
  'event ForgeFulfilled(address indexed buyer, uint256 indexed requestId, uint256 indexed tokenId, uint256 editionId)',
] as const;
